### ISSUE TITLE
Error while doing normalization

### ISSUE THREAD

**Issue by amardeepjaiman** [themmes/pointcloud-example-notebooks#2]
I am getting following error in Compute grid hash step while data preprocessing.

TypeError                                 Traceback (most recent call last)
<ipython-input-25-a97b2e39b2e4> in <module>
      1 df['hash'] = df[['X', 'Y']].apply(get_hash, grid_size=grid_size, meta=('hash', int), axis=1)
----> 2 print(df.head())

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/dataframe/core.py in head(self, n, npartitions, compute)
    874 
    875         if compute:
--> 876             result = result.compute()
    877         return result
    878 

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
    154         dask.base.compute
    155         """
--> 156         (result,) = compute(self, traverse=False, **kwargs)
    157         return result
    158 

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    395     keys = [x.__dask_keys__() for x in collections]
    396     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 397     results = schedule(dsk, keys, **kwargs)
    398     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    399 

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, **kwargs)
     74     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     75                         cache=cache, get_id=_thread_get_id,
---> 76                         pack_exception=pack_exception, **kwargs)
     77 
     78     # Cleanup pools associated to dead threads

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    499                         _execute_task(task, data)  # Re-execute locally
    500                     else:
--> 501                         raise_exception(exc, tb)
    502                 res, worker_id = loads(res_info)
    503                 state['cache'][key] = res

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/compatibility.py in reraise(exc, tb)
    110         if exc.__traceback__ is not tb:
    111             raise exc.with_traceback(tb)
--> 112         raise exc
    113 
    114 else:

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    270     try:
    271         task, data = loads(task_info)
--> 272         result = _execute_task(task, data)
    273         id = get_id()
    274         result = dumps((result, id))

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/local.py in _execute_task(arg, cache, dsk)
    251         func, args = arg[0], arg[1:]
    252         args2 = [_execute_task(a, cache) for a in args]
--> 253         return func(*args2)
    254     elif not ishashable(arg):
    255         return arg

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/optimization.py in __call__(self, *args)
    940                              % (len(self.inkeys), len(args)))
    941         return _get_recursive(self.dsk, self.outkey,
--> 942                               dict(zip(self.inkeys, args)))
    943 
    944     def __reduce__(self):

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/core.py in _get_recursive(dsk, x, cache)
    130         return cache[x]
    131     elif hashable and x in dsk:
--> 132         res = cache[x] = _get_recursive(dsk, dsk[x], cache)
    133         return res
    134     elif type(x) is tuple and x and callable(x[0]):  # istask

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/core.py in _get_recursive(dsk, x, cache)
    134     elif type(x) is tuple and x and callable(x[0]):  # istask
    135         func, args = x[0], x[1:]
--> 136         args2 = [_get_recursive(dsk, k, cache) for k in args]
    137         return func(*args2)
    138     return x

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/core.py in <listcomp>(.0)
    134     elif type(x) is tuple and x and callable(x[0]):  # istask
    135         func, args = x[0], x[1:]
--> 136         args2 = [_get_recursive(dsk, k, cache) for k in args]
    137         return func(*args2)
    138     return x

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/core.py in _get_recursive(dsk, x, cache)
    134     elif type(x) is tuple and x and callable(x[0]):  # istask
    135         func, args = x[0], x[1:]
--> 136         args2 = [_get_recursive(dsk, k, cache) for k in args]
    137         return func(*args2)
    138     return x

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/core.py in <listcomp>(.0)
    134     elif type(x) is tuple and x and callable(x[0]):  # istask
    135         func, args = x[0], x[1:]
--> 136         args2 = [_get_recursive(dsk, k, cache) for k in args]
    137         return func(*args2)
    138     return x

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/core.py in _get_recursive(dsk, x, cache)
    124     # recursive, no cycle detection
    125     if isinstance(x, list):
--> 126         return [_get_recursive(dsk, k, cache) for k in x]
    127 
    128     hashable = ishashable(x)

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/core.py in <listcomp>(.0)
    124     # recursive, no cycle detection
    125     if isinstance(x, list):
--> 126         return [_get_recursive(dsk, k, cache) for k in x]
    127 
    128     hashable = ishashable(x)

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/core.py in _get_recursive(dsk, x, cache)
    130         return cache[x]
    131     elif hashable and x in dsk:
--> 132         res = cache[x] = _get_recursive(dsk, dsk[x], cache)
    133         return res
    134     elif type(x) is tuple and x and callable(x[0]):  # istask

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/core.py in _get_recursive(dsk, x, cache)
    134     elif type(x) is tuple and x and callable(x[0]):  # istask
    135         func, args = x[0], x[1:]
--> 136         args2 = [_get_recursive(dsk, k, cache) for k in args]
    137         return func(*args2)
    138     return x

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/core.py in <listcomp>(.0)
    134     elif type(x) is tuple and x and callable(x[0]):  # istask
    135         func, args = x[0], x[1:]
--> 136         args2 = [_get_recursive(dsk, k, cache) for k in args]
    137         return func(*args2)
    138     return x

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/core.py in _get_recursive(dsk, x, cache)
    124     # recursive, no cycle detection
    125     if isinstance(x, list):
--> 126         return [_get_recursive(dsk, k, cache) for k in x]
    127 
    128     hashable = ishashable(x)

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/core.py in <listcomp>(.0)
    124     # recursive, no cycle detection
    125     if isinstance(x, list):
--> 126         return [_get_recursive(dsk, k, cache) for k in x]
    127 
    128     hashable = ishashable(x)

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/core.py in _get_recursive(dsk, x, cache)
    135         func, args = x[0], x[1:]
    136         args2 = [_get_recursive(dsk, k, cache) for k in args]
--> 137         return func(*args2)
    138     return x
    139 

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/dataframe/core.py in apply_and_enforce(func, args, kwargs, meta)
   3682 
   3683     Ensures the output has the same columns, even if empty."""
-> 3684     df = func(*args, **kwargs)
   3685     if isinstance(df, (pd.DataFrame, pd.Series, pd.Index)):
   3686         if len(df) == 0:

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/utils.py in __call__(self, obj, *args, **kwargs)
    692 
    693     def __call__(self, obj, *args, **kwargs):
--> 694         return getattr(obj, self.method)(*args, **kwargs)
    695 
    696     def __reduce__(self):

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/pandas/core/frame.py in apply(self, func, axis, broadcast, raw, reduce, result_type, args, **kwds)
   6012                          args=args,
   6013                          kwds=kwds)
-> 6014         return op.get_result()
   6015 
   6016     def applymap(self, func):

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/pandas/core/apply.py in get_result(self)
    140             return self.apply_raw()
    141 
--> 142         return self.apply_standard()
    143 
    144     def apply_empty_result(self):

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/pandas/core/apply.py in apply_standard(self)
    246 
    247         # compute the result using the series generator
--> 248         self.apply_series_generator()
    249 
    250         # wrap results

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/pandas/core/apply.py in apply_series_generator(self)
    275             try:
    276                 for i, v in enumerate(series_gen):
--> 277                     results[i] = self.f(v)
    278                     keys.append(v.name)
    279             except Exception as e:

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/pandas/core/apply.py in f(x)
     72         if kwds or args and not isinstance(func, np.ufunc):
     73             def f(x):
---> 74                 return func(x, *args, **kwds)
     75         else:
     76             f = func

<ipython-input-22-0a4ff9bef046> in get_hash(point, grid_size)
      1 def get_hash(point, grid_size=grid_size):
----> 2     return m.pack((point.X // grid_size), (point.Y // grid_size))

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/morton.py in pack(self, *args)
     86         code = 0
     87         for i in range(self.dimensions):
---> 88             code |= self.split(args[i]) << i
     89         return code
     90 

~/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/morton.py in split(self, value)
     52         lshifts = self.lshifts
     53         for o in range(len(masks)):
---> 54             value = (value | (value << lshifts[o])) & masks[o]
     55         return value
     56 

TypeError: ("unsupported operand type(s) for <<: 'numpy.float64' and 'int'", 'occurred at index 0')

**Comment by davdmaccartney** [comment]
me too:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<timed eval> in <module>

~/.virtualenvs/cv/lib/python3.6/site-packages/dask/dataframe/core.py in to_parquet(self, path, *args, **kwargs)
   2814         """ See dd.to_parquet docstring for more information """
   2815         from .io import to_parquet
-> 2816         return to_parquet(self, path, *args, **kwargs)
   2817 
   2818     @derived_from(pd.DataFrame)

~/.virtualenvs/cv/lib/python3.6/site-packages/dask/dataframe/io/parquet.py in to_parquet(df, path, engine, compression, write_index, append, ignore_divisions, partition_on, storage_options, compute, **kwargs)
   1231 
   1232     if compute:
-> 1233         out.compute()
   1234         return None
   1235     return out

~/.virtualenvs/cv/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
    154         dask.base.compute
    155         """
--> 156         (result,) = compute(self, traverse=False, **kwargs)
    157         return result
    158 

~/.virtualenvs/cv/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    396     keys = [x.__dask_keys__() for x in collections]
    397     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 398     results = schedule(dsk, keys, **kwargs)
    399     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    400 

~/.virtualenvs/cv/lib/python3.6/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     74     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     75                         cache=cache, get_id=_thread_get_id,
---> 76                         pack_exception=pack_exception, **kwargs)
     77 
     78     # Cleanup pools associated to dead threads

~/.virtualenvs/cv/lib/python3.6/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    457                         _execute_task(task, data)  # Re-execute locally
    458                     else:
--> 459                         raise_exception(exc, tb)
    460                 res, worker_id = loads(res_info)
    461                 state['cache'][key] = res

~/.virtualenvs/cv/lib/python3.6/site-packages/dask/compatibility.py in reraise(exc, tb)
    110         if exc.__traceback__ is not tb:
    111             raise exc.with_traceback(tb)
--> 112         raise exc
    113 
    114     import pickle as cPickle

~/.virtualenvs/cv/lib/python3.6/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    228     try:
    229         task, data = loads(task_info)
--> 230         result = _execute_task(task, data)
    231         id = get_id()
    232         result = dumps((result, id))

~/.virtualenvs/cv/lib/python3.6/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

~/.virtualenvs/cv/lib/python3.6/site-packages/dask/optimization.py in __call__(self, *args)
    940                              % (len(self.inkeys), len(args)))
    941         return core.get(self.dsk, self.outkey,
--> 942                         dict(zip(self.inkeys, args)))
    943 
    944     def __reduce__(self):

~/.virtualenvs/cv/lib/python3.6/site-packages/dask/core.py in get(dsk, out, cache)
    147     for key in toposort(dsk):
    148         task = dsk[key]
--> 149         result = _execute_task(task, cache)
    150         cache[key] = result
    151     result = _execute_task(out, cache)

~/.virtualenvs/cv/lib/python3.6/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

~/.virtualenvs/cv/lib/python3.6/site-packages/dask/compatibility.py in apply(func, args, kwargs)
     91     def apply(func, args, kwargs=None):
     92         if kwargs:
---> 93             return func(*args, **kwargs)
     94         else:
     95             return func(*args)

~/.virtualenvs/cv/lib/python3.6/site-packages/dask/dataframe/core.py in apply_and_enforce(*args, **kwargs)
   3776     func = kwargs.pop('_func')
   3777     meta = kwargs.pop('_meta')
-> 3778     df = func(*args, **kwargs)
   3779     if is_dataframe_like(df) or is_series_like(df) or is_index_like(df):
   3780         if len(df) == 0:

~/.virtualenvs/cv/lib/python3.6/site-packages/dask/utils.py in __call__(self, obj, *args, **kwargs)
    695 
    696     def __call__(self, obj, *args, **kwargs):
--> 697         return getattr(obj, self.method)(*args, **kwargs)
    698 
    699     def __reduce__(self):

~/.virtualenvs/cv/lib/python3.6/site-packages/pandas/core/frame.py in apply(self, func, axis, broadcast, raw, reduce, result_type, args, **kwds)
   6494                          args=args,
   6495                          kwds=kwds)
-> 6496         return op.get_result()
   6497 
   6498     def applymap(self, func):

~/.virtualenvs/cv/lib/python3.6/site-packages/pandas/core/apply.py in get_result(self)
    149             return self.apply_raw()
    150 
--> 151         return self.apply_standard()
    152 
    153     def apply_empty_result(self):

~/.virtualenvs/cv/lib/python3.6/site-packages/pandas/core/apply.py in apply_standard(self)
    255 
    256         # compute the result using the series generator
--> 257         self.apply_series_generator()
    258 
    259         # wrap results

~/.virtualenvs/cv/lib/python3.6/site-packages/pandas/core/apply.py in apply_series_generator(self)
    284             try:
    285                 for i, v in enumerate(series_gen):
--> 286                     results[i] = self.f(v)
    287                     keys.append(v.name)
    288             except Exception as e:

~/.virtualenvs/cv/lib/python3.6/site-packages/pandas/core/apply.py in f(x)
     76 
     77             def f(x):
---> 78                 return func(x, *args, **kwds)
     79         else:
     80             f = func

<ipython-input-20-0a4ff9bef046> in get_hash(point, grid_size)
      1 def get_hash(point, grid_size=grid_size):
----> 2     return m.pack((point.X // grid_size), (point.Y // grid_size))

~/Desktop/las-python/morton.py in pack(self, *args)
     86         code = 0
     87         for i in range(self.dimensions):
---> 88             code |= self.split(args[i]) << i
     89         return code
     90 

~/Desktop/las-python/morton.py in split(self, value)
     52         lshifts = self.lshifts
     53         for o in range(len(masks)):
---> 54             value = (value | (value << lshifts[o])) & masks[o]
     55         return value
     56 

TypeError: ("ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''", 'occurred at index 0')

**Comment by themmes** [comment]
Interesting error, pymorton seems quite strict on inputtypes. I will try to reproduce after my holiday!

**Comment by davdmaccartney** [comment]
Hi it's working now, the problem was that the '//' return a float like (5.0) just converted it to an int and it's working fine, by the way I also changed your Las importer to get the real values of the points : 
@delayed
def load(file):
    with File(file.as_posix(), mode='r') as las_data:
        las_df = pd.DataFrame(las_data.points['point'], dtype=float).drop(dropped_columns, axis=1)
        Pscale = las_data.header.scale[0]
        Xoffset = las_data.header.offset[0]
        Yoffset = las_data.header.offset[1]
        Zoffeset = las_data.header.offset[2]
        las_df['X'] = (las_df.X*Pscale)+Xoffset
        las_df['Y'] = (las_df.Y*Pscale)+Yoffset
        las_df['Z'] = (las_df.Z*Pscale)+Zoffeset
        return las_df

**Comment by amardeepjaiman** [comment]
Thanks @davdmaccartney . That really helps.

**Comment by amardeepjaiman** [comment]
Hi @davdmaccartney ,  I am getting following error using your code snippet 

Traceback (most recent call last):
  File "prepare_data.py", line 63, in <module>
    print(df.head())
  File "/home/cowi/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/dataframe/core.py", line 876, in head
    result = result.compute()
  File "/home/cowi/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/cowi/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/base.py", line 397, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/cowi/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/threaded.py", line 76, in get
    pack_exception=pack_exception, **kwargs)
  File "/home/cowi/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/local.py", line 501, in get_async
    raise_exception(exc, tb)
  File "/home/cowi/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/compatibility.py", line 112, in reraise
    raise exc
  File "/home/cowi/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/local.py", line 272, in execute_task
    result = _execute_task(task, data)
  File "/home/cowi/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/local.py", line 252, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "/home/cowi/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/local.py", line 252, in <listcomp>
    args2 = [_execute_task(a, cache) for a in args]
  File "/home/cowi/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/dask/local.py", line 253, in _execute_task
    return func(*args2)
  File "prepare_data.py", line 49, in load
    las_df['X'] = (las_df.XPscale)+Xoffset
  File "/home/cowi/anaconda3/envs/lidar_classification/lib/python3.6/site-packages/pandas/core/generic.py", line 4376, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'XPscale'

What is XPscale in your pointcloud dataframe ?

**Comment by davdmaccartney** [comment]
Hi @amardeepjaiman, XPscale is the scale factor of the Las file, do you have a standard header in your las files, look at : https://pythonhosted.org/laspy/header.html

**Comment by davdmaccartney** [comment]
Hi @themmes, so I corrected a few errors, like the json file name, I also changed the load_data_memory to use the correct hash column name and so on, but now I'm stuck with the model.py from the original Pointnet, I think you modified yours, for exemple you are passing 3 arguments to placeholder_inputs, is it possible to get yours version?

**Comment by themmes** [comment]
Hmm I thought I included everything that is custom. I will look at it once I am back home next week. If so i’ll definitely add it to the repo, I am sorry my example is not as smooth as I thought!

**Comment by amardeepjaiman** [comment]
Hi @themmes , Your example for data preparation helps a lot. its just whatever changes you did in model.py to call from custom_train.py , please also include that. So that we can run that straighaway. I am also stuck at same point where @davdmaccartney got stuck.

**Comment by davdmaccartney** [comment]
Never mind it's already great to share your exemple, debugging is a clever way to learn ! Talk to you next week then, wishing you a happy holidays end!

**Comment by davdmaccartney** [comment]
Hi @amardeepjaiman, i noticed that you are working for COWI, could you send me an email I would like to exchange with you !

**Comment by themmes** [comment]
Hi @davdmaccartney,

Problem was I added Pointnet as a submodule to my project but did not store the changed `model.py` file. However, I was able to reproduce my changes and added the `model_custom.py` to this repo.

To elaborate; I made changes to both the `placeholder_inputs()` and `get_model()` function. The changes are as simple as adding the `POINT_DIM` parameter to both functions and replacing all the hardcoded `9` values for `POINT_DIM`. Note, in the `if __name__ == '__main__'` part of this file the shape of the input is hardcoded, I left these in for now. @davdmaccartney Maybe you can confirm whether it is working for you this way?

**Comment by themmes** [comment]
@amardeepjaiman Was your issue resolved by the improvements made by @davdmaccartney ?

**Comment by davdmaccartney** [comment]
@themmes thanks for the feedback will have a look later and let you know, best

**Comment by amardeepjaiman** [comment]
Hi @themmes ,

Thanks for responding. Yeah after doing changes i was able to process the point cloud data in normalized format. But when I start using train_custom.py i encountered similar issue related to hardcoded value of POINT_DIM. which i corrected. After these changes I get one more error , for that i would provide the error traces to you shortly. probably you can suggest something.

**Comment by themmes** [comment]
Thanks for your quick response, it seems the issues raised in this issue are solved for now. Would you be able to put the changes you made into a PR? Because, now we both put effort in changing the `model.py`.

If you could place your new traces in a new issue that would keep things more clear for others.

Thanks in advance!

**Comment by davdmaccartney** [comment]
Hi @themmes still not working, I'm facing an issue with the hash, in your train_custom your hash column is concatenated with the grid size, however in your notebook pipeline your column is 'hash' : 
-> KeyError: "['hash1m']"
and when I change the name in the train_custom to 'hash', we get an index error,
ValueError: 'hash' is both an index level and a column label, which is ambiguous.
I'm a bit confused, thanks for your help...

**Comment by Tojens** [comment]
Hi

Did you ever find a solution to this issue @davdmaccartney? I am having the same problem, so any help would be much appreciated :)

**Comment by davdmaccartney** [comment]
Hi yes it working fine, bellow the code I'm using 

def get_hash(row):
    return m.pack(row['mX'],row['mY'])

 # hash
    df['mX'] = df.X // grid_size
    df.mX = df.mX.astype(int)
    df['mY'] = df.Y // grid_size
    df.mY = df.mY.astype(int)
    df['hash'] = df[['mX', 'mY']].apply(get_hash, axis=1)
